name: Blossom-CI
on: [push, workflow_dispatch]
jobs:        
          
  Job-trigger:
    name: Start ci job
    runs-on: self-hosted
    steps:
      - name: Start ci job
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server: "http://10.137.149.25:8080/"
          jenkins-job: "My-Pipeline"
