# Copyright (c) 2020-2021, NVIDIA CORPORATION.

name: Blossom-CI
on: [push]
jobs:        
          
  Job-trigger:
    name: Start ci job
    runs-on: self-hosted
    steps:
      - name: Start ci job
        run: blossom-ci
        env:
          OPERATION: 'START-CI-JOB'
          CI_SERVER: ${{ secrets.CI_SERVER }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
