# Copyright (c) 2020-2021, NVIDIA CORPORATION.
name: Hello-World
on: [push, workflow_dispatch]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - name: Say Hello World
        run: echo Hello, world!
